spring:
  application:
    name: api-invocation
  # MongoDB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: api_invocation

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true