spring:
  application:
    name: api-invocation
  data:
    mongodb:
      host: mongodb-gatcha
      database: api_invocation
      port: 27017
      username: root
      password: example
      authentication-database: admin
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
  instance:
    preferIpAddress: true