spring:
  application:
    name: api-invocation
  data:
    mongodb:
      host: localhost
      database: api_invocation
      port: 27019
      username: root
      password: azerty
      authentication-database: admin