server:
  port: 8082
spring:
  application:
    name: api-invocation
  data:
    mongodb:
      host: localhost
      database: api_invocation
      port: 27019
      username: root
      password: example
      authentication-database: admin
  cloud:
    openfeign:
      client:
        config:
          api-monster:
            url: "http://localhost:8083/"
          api-player:
            url: "http://localhost:8081/"
springdoc:
  api-docs:
    path: "/invocation-api/docs"
  swagger-ui:
    path: "/invocation-api/swagger-ui.html"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true