server:
  port: 8080
spring:
  application:
    name: api-authentication
  data:
    mongodb:
      host: mongodb-gatcha
      database: api_auth
      port: 27017
      username: root
      password: example
      authentication-database: admin
springdoc:
  api-docs:
    path: "/auth-api/docs"
  swagger-ui:
    path: "/auth-api/swagger-ui.html"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
jwt:
  private:
    file: certs/private.pem
  public:
    file: certs/public.pem