spring:
  application:
    name: api-auth
  data:
    mongodb:
      host: mongodb-gatcha
      database: api_auth
      port: 27017
      username: root
      password: example
      authentication-database: admin
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
