server:
  port: 8080
spring:
  application:
    name: api-authentication
  data:
    mongodb:
      host: localhost
      database: api_auth
      port: 27019
      username: root
      password: example
      authentication-database: admin
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
jwt:
  private:
    file: certs/jwt_private.pem