spring:
  data:
    mongodb:
      host: localhost
      database: api_auth
      port: 27017

token:
  expiration: 1000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka