server:
  port: 8084
spring:
  application:
    name: api-combat
  data:
    mongodb:
      host: localhost
      database: api_combat
      port: 27019
      username: root
      password: example
      authentication-database: admin
  cloud:
    openfeign:
      client:
        config:
          api-monster:
            url: "http://localhost:8083/"
springdoc:
  api-docs:
    path: "/combat-api/v3/api-docs"
    enabled: true
  swagger-ui:
    path: "/combat-api/swagger-ui.html"
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true