services:
  openssl-keygen:
    build:
      dockerfile: ./docker-conf/openssl/Dockerfile
    image: openssl-keygen:latest
    container_name: openssl-keygen

  mongodb-gatcha:
    image: mongo
    container_name: mongodb-gatcha
    env_file: "./docker-conf/mongodb/docker.env"
    volumes:
      - "./docker-conf/mongodb/init/:/docker-entrypoint-initdb.d"
      - "./docker-conf/mongodb/seed:/seed"
      - "mongodb-gatcha:/data/db"
    expose:
      - 27017
    ports:
      - "27019:27017"
    restart: on-failure
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  discovery-server:
    build:
      dockerfile: ./discovery-server/Dockerfile
    container_name: discovery-server
    links:
      - mongodb-gatcha
    restart: on-failure
    healthcheck:
      test: echo "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"

  auth-api:
    build:
      dockerfile: ./api-auth/Dockerfile
      args:
        PRIVATE_KEY_PATH: "/openssl/certs/private/private.pem"
    container_name: auth-api
    links:
      - mongodb-gatcha
    restart: on-failure
    healthcheck:
      test: echo "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
    depends_on:
      openssl-keygen:
        condition: service_completed_successfully
      mongodb-gatcha:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

  gateway-api:
    build:
      dockerfile: ./api-gateway/Dockerfile
      args:
        PUBLIC_KEY_PATH: "/openssl/certs/public/public.pem"
    container_name: gateway-api
    ports:
      - "8888:8888"
    links:
      - mongodb-gatcha
    restart: on-failure
    healthcheck:
      test: echo "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
    depends_on:
      auth-api:
        condition: service_healthy

  player-api:
    build:
      dockerfile: ./api-player/Dockerfile
    container_name: player-api
    links:
      - mongodb-gatcha
    restart: on-failure
    depends_on:
      mongodb-gatcha:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

  invocation-api:
    build:
      dockerfile: ./api-invocation/Dockerfile
    container_name: invocation-api
    links:
      - mongodb-gatcha
    restart: on-failure
    depends_on:
      mongodb-gatcha:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

  monster-api:
    build:
      dockerfile: ./api-monster/Dockerfile
    container_name: monster-api
    links:
      - mongodb-gatcha
    restart: on-failure
    depends_on:
      mongodb-gatcha:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    volumes:
      - "./docker-conf/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  mongodb-gatcha:
