services:
  mongodb-gatcha:
    image: mongo
    container_name: mongodb-gatcha
    env_file: "./docker-conf/mongodb/docker.env"
    volumes:
      - "./docker-conf/mongodb/init/:/docker-entrypoint-initdb.d"
      - "./docker-conf/mongodb/seed:/seed"
      - "mongodb-gatcha:/data/db"
    expose:
      - 27017
    ports:
      - "27019:27017"
    restart: on-failure
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  discovery-server:
    build:
      dockerfile: ./discovery-server/Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    links:
      - mongodb-gatcha
    restart: on-failure
    healthcheck:
      test: echo "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"

#  auth-api:
#    build:
#      dockerfile: ./api-auth/Dockerfile
#    container_name: auth-api
#    ports:
#      - "8080:8080"
#    links:
#      - mongodb-gatcha
#    restart: on-failure
#    depends_on:
#      mongodb-gatcha:
#        condition: service_healthy
#      discovery-server:
#        condition: service_healthy

  player-api:
    build:
      dockerfile: ./api-player/Dockerfile
    container_name: player-api
    ports:
      - "8081:8080"
    links:
      - mongodb-gatcha
    restart: on-failure
    depends_on:
      mongodb-gatcha:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

  invocation-api:
    build:
      dockerfile: ./api-invocation/Dockerfile
    container_name: invocation-api
    ports:
      - "8082:8080"
    links:
      - mongodb-gatcha
    restart: on-failure
    depends_on:
      mongodb-gatcha:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

  monster-api:
    build:
      dockerfile: ./api-monster/Dockerfile
    container_name: monster-api
    ports:
      - "8083:8080"
    links:
      - mongodb-gatcha
    restart: on-failure
    depends_on:
      mongodb-gatcha:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    volumes:
      - "./docker-conf/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  mongodb-gatcha:
