server:
  port: 8888
  shutdown: graceful
  error:
    include-exception: false
    include-path: never
    include-stacktrace: never
    include-binding-errors: never

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: api-authentication
          uri: lb://api-authentication
          predicates:
            - Path=/auth-api/v1/auth/**

        - id: api-player
          uri: lb://api-player
          predicates:
            - Path=/player-api/v1/players/**
          filters:
            - AuthenticationFilter
  main:
    web-application-type: reactive

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoint:
    gateway:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "*"
