server:
  port: 8888
  shutdown: graceful
  error:
    include-exception: false
    include-path: never
    include-stacktrace: never
    include-binding-errors: never

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://frontend:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: api-authentication
          uri: lb://api-authentication
          predicates:
            - Path=/auth-api/**

        - id: api-player
          uri: lb://api-player
          predicates:
            - Path=/player-api/**
          filters:
            - AuthenticationFilter

        - id: api-monster
          uri: lb://api-monster
          predicates:
            - Path=/monster-api/**
          filters:
            - AuthenticationFilter

        - id: api-invocation
          uri: lb://api-invocation
          predicates:
            - Path=/invocation-api/**
          filters:
            - AuthenticationFilter

        - id: api-combat
          uri: lb://api-combat
          predicates:
            - Path=/combat-api/**
          filters:
            - AuthenticationFilter

        - id: block-all
          uri: "no://op"
          predicates:
            - Path=/{segment:^(?!swagger-ui|v3\/api-docs).*$}/**
          filters:
            - name: SetStatus
              args:
                status: 404
  main:
    web-application-type: reactive

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: API Gateway
        url: /v3/api-docs
      - name: Authentication Service
        url: /auth-api/v3/api-docs
      - name: Player Service
        url: /player-api/v3/api-docs
      - name: Invocation Service
        url: /invocation-api/v3/api-docs
      - name: Monster Service
        url: /monster-api/v3/api-docs
      - name: Combat Service
        url: /combat-api/v3/api-docs

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoint:
    gateway:
      access: unrestricted
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
jwt:
  public:
    file: certs/public.pem