server:
  port: 8083

spring:
  application:
    name: api-monster
  data:
    mongodb:
      host: localhost
      database: api_monster
      port: 27019
      username: root
      password: example
      authentication-database: admin
springdoc:
  api-docs:
    path: "/monster-api/v3/api-docs"
    enabled: true
  swagger-ui:
    path: "/monster-api/swagger-ui.html"
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true