spring:
  application:
    name: api-monster
  # MongoDB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: monsterAPI

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true