spring:
  application:
    name: api-monster
  data:
    mongodb:
      host: mongodb-gatcha
      database: api_monster
      port: 27017
      username: root
      password: example
      authentication-database: admin
springdoc:
  api-docs:
    path: "/monster-api/docs"
  swagger-ui:
    path: "/monster-api/swagger-ui.html"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always