server:
  port: 8081

spring:
  application:
    name: api-player
  data:
    mongodb:
      host: localhost
      database: api_player
      port: 27019
      username: root
      password: example
      authentication-database: admin
springdoc:
  api-docs:
    path: "/player-api/docs"
  swagger-ui:
    path: "/player-api/swagger-ui.html"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true